### ISSUE TITLE
The request cannot be fulfilled because of the state of another resource. - The resource 'appPrices' cannot be viewed, created or updated. Please view and create 'manualPrices' using the resource 'appPriceSchedules'.

### ISSUE THREAD

**Issue by walter-ayala** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#130]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.21.6
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)?  NOT APPLICABLE

### Issue description

I want deploy my React Native app in App Store but the step fails with the message: The request cannot be fulfilled because of the state of another resource. - The resource 'appPrices' cannot be viewed, created or updated. Please view and create 'manualPrices' using the resource 'appPriceSchedules'

And also show a warning/advertisement : Listing apps fails, due to the recent pricing update on App Store?

I don't use fastlane.

The step worked before, but now as App Store changed its price section and when I fill the information in the section with the price in the different countries it started to give this error, probably I have to change something in the step to configure that section of the AppStore.

### Bitrise info

- Build URL: https://app.bitrise.io/build/befc66cd-115b-4921-8073-32f859646e92
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES 
- Log: If you have issues, use the latest prerelease version of fastlane.
           Set the fastlane version input to "latest" to enable prerelease versions.
           Deploy failed, error: exit status 1

<details>
  <pre>
Config:
- ipa_path: /Users/vagrant/deploy/########.ipa
- pkg_path: <unset>
- connection: api_key
- itunescon_user: <unset>
- password: <unset>
- app_password: <unset>
- api_key_path: <unset>
- api_issuer: <unset>
- app_id: <unset>
- bundle_id: #####
- submit_for_review: no
- skip_metadata: yes
- skip_screenshots: yes
- skip_app_version_update: no
- team_id: <unset>
- team_name: <unset>
- platform: ios
- options: <unset>
- gemfile_path: ./Gemfile
- fastlane_version: latest-stable
- itms_upload_parameters: <unset>
- verbose_log: false
- BITRISE_BUILD_URL: https://app.bitrise.io/build/befc66cd-115b-4921-8073-32f859646e92
- BITRISE_BUILD_API_TOKEN: *****
Bitrise Apple Developer Connection with API key found
Setup
fastlane version defined: latest-stable, installing...
$ gem "install" "fastlane" "--no-document"
$ rbenv "rehash"
$ fastlane "-v"
fastlane installation at path:
/Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/bin/fastlane
-----------------------------
fastlane 2.212.1
Setup took 6.931938 seconds to complete
Deploy
$ fastlane "deliver" "--api_key_path" "/var/folders/dw/lz_9l61x0y9089f673sqt55h0000gn/T/apiKey1974645242/api_key.json" "--precheck_include_in_app_purchases" "false" "--app_identifier" "app.#####.ios" "--ipa" "/var/folders/dw/lz_9l61x0y9089f673sqt55h0000gn/T/ipaOrPkg2648974573/tmp.ipa" "--skip_screenshots" "--skip_metadata" "--force" "--platform" "ios"
[00:15:48]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[00:15:49]: Creating authorization token for App Store Connect API
Looking for related GitHub issues on fastlane/fastlane...
➡️  Listing apps fails, due to the recent pricing update on App Store?
    https://github.com/fastlane/fastlane/issues/21125 [open] 29 💬
    2 hours ago
🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': \e[31m[!] The request cannot be fulfilled because of the state of another resource. - The resource 'appPrices' cannot be viewed, created or updated. Please view and create 'manualPrices' using the resource 'appPriceSchedules'.\e[0m (Spaceship::UnexpectedResponse)
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:22:in `get_apps'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/2.7.0/forwardable.rb:235:in `get_apps'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/models/app.rb:75:in `all'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/models/app.rb:81:in `find'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/detect_values.rb:46:in `find_app'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/detect_values.rb:17:in `run!'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/runner.rb:25:in `initialize'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/commands_generator.rb:82:in `new'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/commands_generator.rb:82:in `block (2 levels) in run'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/commands_generator.rb:187:in `run'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/commands_generator.rb:18:in `start'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/bin/fastlane:23:in `<top (required)>'
	from /Users/vagrant/.rbenv/versions/2.7.6/bin/fastlane:23:in `load'
	from /Users/vagrant/.rbenv/versions/2.7.6/bin/fastlane:23:in `<main>'
/Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': The request cannot be fulfilled because of the state of another resource. - The resource 'appPrices' cannot be viewed, created or updated. Please view and create 'manualPrices' using the resource 'appPriceSchedules'. (Spaceship::UnexpectedResponse)
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:22:in `get_apps'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/2.7.0/forwardable.rb:235:in `get_apps'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/models/app.rb:75:in `all'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/models/app.rb:81:in `find'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/detect_values.rb:46:in `find_app'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/detect_values.rb:17:in `run!'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/runner.rb:25:in `initialize'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/commands_generator.rb:82:in `new'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/commands_generator.rb:82:in `block (2 levels) in run'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/commands_generator.rb:187:in `run'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/commands_generator.rb:18:in `start'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /Users/vagrant/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/bin/fastlane:23:in `<top (required)>'
	from /Users/vagrant/.rbenv/versions/2.7.6/bin/fastlane:23:in `load'
	from /Users/vagrant/.rbenv/versions/2.7.6/bin/fastlane:23:in `<main>'
If you have issues, use the latest prerelease version of fastlane.
Set the fastlane version input to "latest" to enable prerelease versions.
Deploy failed, error: exit status 1
  </pre>
</details>

The .yml part for this step:
 - deploy-to-itunesconnect-deliver@2:
        inputs:
        - bundle_id: "$IOS_BUNDLE_ID"
        - submit_for_review: "$IOS_SUBMIT_FOR_REVIEW"
        - skip_metadata: "$IOS_SKIP_METADATA"
        - skip_screenshots: "$IOS_SKIP_SCREENSHOTS"
        - connection: api_key

I also talked to bitrise support and they gave me the following solution: https://github.com/fastlane/fastlane/issues/21125#issuecomment-1464684522 but it doesn't apply in my case as I don't use fastlane directly.

**Comment by Gambitboy** [comment]
They seem to deployed a fix. But my project is still getting issue.

```
[10:27:37]: Creating authorization token for App Store Connect API
[10:27:37]: wrong number of arguments (given 2, expected 1)
/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rubyzip-3.0.0.alpha/lib/zip/file.rb:92:in `open'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:68:in `fetch_info_plist_with_rubyzip'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:41:in `fetch_info_plist_file'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:18:in `fetch_app_version'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.2/deliver/lib/deliver/detect_values.rb:73:in `find_version'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.2/deliver/lib/deliver/detect_values.rb:20:in `run!'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.2/deliver/lib/deliver/runner.rb:25:in `initialize'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.2/deliver/lib/deliver/commands_generator.rb:82:in `new'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.2/deliver/lib/deliver/commands_generator.rb:82:in `block (2 levels) in run'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.2/deliver/lib/deliver/commands_generator.rb:187:in `run'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.2/deliver/lib/deliver/commands_generator.rb:18:in `start'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'\n/Users/vagrant/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/fastlane-2.212.2/bin/fastlane:23:in `<top (required)>'\n/Users/vagrant/.rbenv/versions/2.7.5/bin/fastlane:23:in `load'\n/Users/vagrant/.rbenv/versions/2.7.5/bin/fastlane:23:in `<main>'
[!] Could not infer your app's version
Deploy failed, error: exit status 1
```

Not sure if this issue is still on their side or this repo.

**Comment by Gambitboy** [comment]
To fastlane itself. I linked the PR above.

**Comment by jarrodparkes** [comment]
@Gambitboy looking at their release notes now https://github.com/fastlane/fastlane/releases which release were you referring to 🤔 ? I didn't see anything for #21125 yet 😢

**Comment by Gambitboy** [comment]
This is the issue I'm currently getting.

It can't seem to auto detect my app version.

`Could not infer your app's version`

Any ideas?

![image](https://github.com/bitrise-steplib/steps-deploy-to-itunesconnect-deliver/assets/15830178/dc2058e0-214d-4fdb-8876-62a12f89b674)

**Comment by Gambitboy** [comment]
Any help here? I'm still getting this wrong number of arguments given

**Comment by Gambitboy** [comment]
I'm still experiencing the issue.
