### ISSUE TITLE
Could not find a version to edit for app 'AppName'

### ISSUE THREAD

**Issue by Gregoirevda** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#48]
We didn't changed our build settings and this error
`[!] Could not find a version to edit for app 'AppName'`
appeared since yesterday.

Can this be related to the recent update to itunesconnect?
Is this related to fastlane or this tool?

itunesconnect deliver: `2.11.0`
fastlane: `2.97.0`
deliver 2.96.1 Summary

**Comment by godrei** [comment]
Hi @Gregoirevda ,
without the build log its hard to identify the issue.
However it seems Fastlane has a similar issue: https://github.com/fastlane/fastlane/issues/1517,
it seems defining the `app_version` input on deliver solves the issue. This input of deliver is not wired in as a step input, but the step has an input: `Additional options for `deliver` call` which you can use to define this option.

**Comment by Gregoirevda** [comment]
Note that this doesn't occur if you set `skip_app_version_update ` to false
