### ISSUE TITLE
Phased release not being set on App Store Connect

### ISSUE THREAD

**Issue by ruipfcosta** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#59]
I recently added the option to use phased release when submitting my app to App Store Connect, however that option never gets set on App Store Connect, which just looks like this:

<img width="1161" alt="screenshot 2019-02-04 at 10 59 30" src="https://user-images.githubusercontent.com/1910006/52204471-1ecf6c80-286c-11e9-98b2-b370c5da3570.png">

#### Command executed

fastlane "deliver" "--username" [username] "--app" [app] "--team_name" [team name] "--ipa" [ipa] "--skip_screenshots" "--skip_metadata" "--force" "--platform" "ios" "--phased_release"

**Comment by bitce** [comment]
Hi @ruipfcosta! Could you send us a build URL of this scenario?
