### ISSUE TITLE
gem install fails trying to install bundler when ensuring fastlane version

### ISSUE THREAD

**Issue by pwoods-al** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#65]
step version: 2.16.0

We seem to be hitting a new issue with ensuring the fastlane version: `"bundle" from bundler conflicts with /Users/vagrant/.rbenv/versions/2.5.3/bin/bundle, error: exit status 1`

We have used the step successfully in the past, as part of retooling some of our workflows over the past few days I updated the step to the latest version, so I'm not sure if something else changed in the process to cause this particular issue to be hit. In looking at the changes for 2.16.0, this does seem to be hit as part of the changed code in that release. I may be able to test with a previous version of the step, but want to be cautious as I don't want to create unnecessary App Store churn if I don't have to.

Here's the relevant lines from the log:

    +------------------------------------------------------------------------------+
    | (0) deploy-to-itunesconnect-deliver                                          |
    +------------------------------------------------------------------------------+
    | id: deploy-to-itunesconnect-deliver                                          |
    | version: 2.16.0                                                              |
    | collection: https://github.com/bitrise-io/bitrise-steplib.git                |
    | toolkit: go                                                                  |
    | time: 2019-07-18T21:30:02Z                                                   |
    +------------------------------------------------------------------------------+
    |                                                                              |
    
    ...

    Ensure cookies for Apple Developer Portal
    Session exported
    Setup
    fastlane version defined: latest, installing...
    2 attempt failed
    3 attempt failed
    Failed to ensure fastlane version, error: gem install command failed, output: ERROR:  Error installing fastlane:
        "bundle" from bundler conflicts with /Users/vagrant/.rbenv/versions/2.5.3/bin/bundle, error: exit status 1
    |                                                                              |
    +---+---------------------------------------------------------------+----------+
    | x | deploy-to-itunesconnect-deliver (exit code: 1)                | 21 sec   |
    +---+---------------------------------------------------------------+----------+
    | Issue tracker: ...trise-steplib/steps-deploy-to-itunesconnect-deliver/issues |
    | Source: .../github.com/bitrise-steplib/steps-deploy-to-itunesconnect-deliver |
    +---+---------------------------------------------------------------+----------+

**Comment by bitce** [comment]
Hi @pwoods-al!

Thanks for your report! We started looking into this, in the while you could solve this by inserting a script step right before the deploy one, with the following input:

```
#!/bin/bash
set -ex
gem install bundler --force
```

**Comment by ios-dev-drivingthru** [comment]
Hey @bitce -

I encountered this issue and tried adding the script, but am still encountering the same error. Any thoughts? Here's a screenshot of my workflow. Thank You!
<img width="1144" alt="Screen Shot 2019-11-07 at 9 44 17 AM" src="https://user-images.githubusercontent.com/57416523/68413569-5a70cd00-0143-11ea-8860-bd79b3472d6a.png">

**Comment by lpusok** [comment]
Hi @ios-dev-drivingthru, @pwoods-al,
Can you try `gem uninstall bundler -a` in a script step before the deploy-to-itunesconnect-deliver step?
If that does not work out please send over the build URL you experienced the issue.

**Comment by vfxdrummer** [comment]
Hi Ipusok - I apologize, I must have solved this issue as our CI is now properly working, but do not remember what fixed it. I feel bad, I should have responded to this comment. My apologies.

**Comment by Roland-Bak** [comment]
Hey @vfxdrummer, no worries, the point is that everything is working correctly now :)
