### ISSUE TITLE
FASTLANE_SESSION env var exposed

### ISSUE THREAD

**Issue by FinHorsley** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#68]
My Go isn't great, but it looks like there is a `FASTLANE_SESSION` env var exposed by the step?
```
if err := tools.ExportEnvironmentWithEnvman("FASTLANE_SESSION", fs); err != nil {
			fail("Failed to export FASTLANE_SESSION, error: %s", err)
		}

		if err := os.Setenv("FASTLANE_SESSION", fs); err != nil {
			fail("Failed to set FASTLANE_SESSION env, error: %s", err)
		}
```

Should this be available in the Bitrise Editor, instead of `No output variables generated by this step`

**Comment by godrei** [comment]
Hi @FinHorsley , sorry for the late response!

Very good point, we should mark all the exposed env vars as step outputs.

In the recent versions we changed this behavior, authentication-related env vars are not exposed anymore. 
We [prepare the required env vars](https://github.com/bitrise-steplib/steps-deploy-to-itunesconnect-deliver/blob/2.20.1/main.go#L397) and [expose them only for the Fastlane command](https://github.com/bitrise-steplib/steps-deploy-to-itunesconnect-deliver/blob/2.20.1/main.go#L481).

I'll close this issue, but if you need more info/help just let us know by opening a new one!
