### ISSUE TITLE
How to add Release Note?

### ISSUE THREAD

**Issue by CHOIMINSEOK** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#69]
I couldn't find out on docs. 
pls give me reference or guide. thanks!

**Comment by bitce** [comment]
The step has this input field, called “options” (https://github.com/bitrise-steplib/steps-deploy-to-itunesconnect-deliver/blob/master/step.yml#L172). With this you can pass extra data to the deliver command through the yml

**Comment by CHOIMINSEOK** [comment]
Thanks! 

I tried to pass extra options `-m upload -f ./.itmsp/ -v eXtreme -t Aspera`, but the connection is failure. 
```
[13:56:32]: [Transporter Error Output]: The option: "-f" may only be specified once.
[13:56:32]: Transporter transfer failed.
[13:56:32]: 
[13:56:32]: The option: "-f" may only be specified once.
```

Seems nothing wrong on parameter for iTMSTransporter. 
Any help for me? ;(

Here is build url! 
https://app.bitrise.io/build/a20c3001a589d3de#?tab=log

**Comment by CHOIMINSEOK** [comment]
I Found it. Referring fastlane docs is really helpful for me.
