### ISSUE TITLE
What is default value of IDFA setting for Review Submit?

### ISSUE THREAD

**Issue by CHOIMINSEOK** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#70]
I cannot find any regarding options.

**Comment by Roland-Bak** [comment]
Hi there @CHOIMINSEOK!

Since the IDFA is a unique ID for each iOS device, this is not something that would have a default value when submitting your build. This is something that is set in your project 🙂

**Comment by CHOIMINSEOK** [comment]
Thank you for response! :)
you mean, this configuration could be done in my project? @Roland-Bak  

![image](https://user-images.githubusercontent.com/20822017/64934938-e162a100-d888-11e9-8d29-6b1694c0662d.png)

**Comment by bitce** [comment]
Hi @CHOIMINSEOK,

According to our research, yes, that is the case. Specifically in your fastfile: https://docs.fastlane.tools/actions/appstore/#compliance-and-idfa-settings

**Comment by CHOIMINSEOK** [comment]
Hmm, I checked that documents but little bit confused. 

> Use the submission_information parameter for additional submission specifiers, including compliance and IDFA settings.

How do I use submission_information parameter in `Bitrise` Console?

**Comment by CHOIMINSEOK** [comment]
힘든 싸움이었다..

**Comment by CHOIMINSEOK** [comment]
Any update for it? @bitce @Roland-Bak

**Comment by Roland-Bak** [comment]
Hey there 👋

Sorry for the late reply. Here is an example where you can see how this parameter should be used: https://github.com/artsy/eigen/blob/faa02e2746194d8d7c11899474de9c517435eca4/fastlane/Fastfile#L131-L149

Hope this helps!

**Comment by d-date** [comment]
You may not understand this question but this is important for submit binary via Bitrise CI.
When not specify `submission_information` , the CI will be failed.

```
[!] Use of Advertising Identifier (IDFA) is required to submit
Add information to the :submission_information option...
  Docs: http://docs.fastlane.tools/actions/deliver/#compliance-and-idfa-settings
  Example: submission_information: { add_id_info_uses_idfa: false }
  Example: submission_information: {
    add_id_info_uses_idfa: true,
    add_id_info_serves_ads: false,
    add_id_info_tracks_install: true,
    add_id_info_tracks_action: true,
    add_id_info_limits_tracking: true
  }
  Example CLI:
    --submission_information "{\"add_id_info_uses_idfa\": false}"
```

Please consider to add submission_information into your UI.

**Comment by d-date** [comment]
Note: This is occurred when specified `submit_for_review: true`

**Comment by non-binary** [comment]
Hi @d-date,

Can you please send a link to a build and enable support access?

**Comment by d-date** [comment]
@non-binary I can't since remote build are now broken. I can only run build on my local and reproduce it.

**Comment by non-binary** [comment]
@d-date I am confused. Is this error only happening locally? Or do your remote builds also fail?

**Comment by d-date** [comment]
@non-binary I believe also in remote but I think you don't have to get my remote access since just to fix step.

If you continue to use fastlane deliver, you should follow them.

**Comment by non-binary** [comment]
Hi @d-date,

Please provide a link to a build on bitrise.io so we can investigate further. This is super helpful in investigating problems rather than setting up a completely new project, trying to reproduce, etc etc. Thank you.

**Comment by gabriprat** [comment]
Hi @non-binary, here's a link to a build with the problem: https://app.bitrise.io/build/ed94bd29556355fe

**Comment by non-binary** [comment]
Hi @gabriprat,

Please enable support access.

**Comment by gabriprat** [comment]
@non-binary done. Meanwhile I managed to fix it by adding this additional command line arguments in the debug section. 
![Screenshot_20200813-163615](https://user-images.githubusercontent.com/302792/90148128-48335780-dd83-11ea-8cad-d8f815c3301f.jpg)

**Comment by non-binary** [comment]
@gabriprat Great to hear! We're here to help if you need anything else.

PS to other folks, please try this as a workaround for now.
