### ISSUE TITLE
Rebrand to "App Store Connect" from "iTunes Connect"

### ISSUE THREAD

**Issue by hkellaway** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#73]
It took me a minute to find this step due to the name. This step could be more discoverable if it was to use the same terms as Apple - namely, they rebranded `iTunes Connect` to `App Store Connect`. This would be especially helpful for newer folks unfamiliar with the former name.

**Comment by bitce** [comment]
Hi @hkellaway!

Thank you for raising this thread despite our awfully long delay in addressing it.

This is true, the reason we have not done this so far is that we've felt this could be just as confusing to older folks, only familiar with the former name and could cause some people difficulty locating the step. 

That said we're looking into making this in the near future, in a way that's as clear as possible to everyone.

**Comment by hkellaway** [comment]
gotcha - thanks for elaborating

**Comment by EyMaddis** [comment]
Simple to solve: `Deploy to AppStore/iTunes Connect` 😄
