### ISSUE TITLE
AppId and Bundleid is not marked as required in form

### ISSUE THREAD

**Issue by slavaGanzin** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#78]
Thanks for your work!

![2020-03-27-165833_1520x400_scrot](https://user-images.githubusercontent.com/1011721/77769349-61de3780-704c-11ea-913d-f6553c55557a.png)

As you can see AppId and BundleId is noted (which is visible only if you try to enter a value) it should be filled, but there is no REQUIRED bage.

Kinda minor inconvenience

**Comment by knox** [comment]
Both App Apple ID and App Bundle ID are not required on their own. Only one of them is required at a time. This is validated during step runtime. There is no way to express this kind of requirement in a step.yml.

**Comment by slavaGanzin** [comment]
@knox you just did

**Comment by cathyharmon** [comment]
Hello,

Thank you for bringing this to our attention.  I will see if we can document this.  I believe @knox may have been referring to marking an input variable as required or optional.  I do not think there is a way to mark them as "one required but not both".

Thanks!
