### ISSUE TITLE
fastlane deliver: Potential server error received: 'Unexpected Error'

### ISSUE THREAD

**Issue by mink-ang** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#81]
https://github.com/fastlane/fastlane/issues/16621

**Comment by bitce** [comment]
Thanks for bringing this to our attention! Have your Bitrise builds started failing with this error? If so, could you link a build URL as an example please?

**Comment by bvd-filigrade** [comment]
Same problem here. 6 hours ago I got an app through but since then all fail on this step with the same error:
https://app.bitrise.io/build/635789dfcf50856d#?tab=log

**Comment by bitce** [comment]
Thanks @bvd-filigrade! We are looking into this ASAP, for the time being we recommend everyone use the Application Loader based deployment step instead.

**Comment by FredTsao** [comment]
I have same issues.
https://app.bitrise.io/build/343fa66a9f45161b#?tab=log

https://github.com/fastlane/fastlane/issues/16621

**Comment by ichina** [comment]
hi guys, can u upgrade the plugin with the latest pre-release of fastlane? https://github.com/fastlane/fastlane/releases

**Comment by sosaucily** [comment]
I don't usually do this, but

+1

**Comment by andreleon** [comment]
As a temporary fix, you can update the fastlane version to the fixed release candidate under "Debug":

![Screenshot 2020-06-25 at 15 33 05](https://user-images.githubusercontent.com/1391492/85729686-50630500-b6f9-11ea-818f-38bc51e4ff76.png)

**Comment by JorisDuboisDPG** [comment]
Release is now available -> https://github.com/fastlane/fastlane/releases/tag/2.150.0
