### ISSUE TITLE
Step never finishes

### ISSUE THREAD

**Issue by EyMaddis** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#84]
My (react-native) app began to no longer finish any production bitrise builds.
If the logs do not lie to me, this step does not complete.
As you can see in the logs, the step is technically done, but leads to a timeout. (09:39:26 is the last log entry, but the build was aborted at around 10:15).

The build times in the full build log only add up to around 50 minutes while the build is aborted after 90 minutes.
Dev builds which basically only differ in this step do not have that problem.

This is happening for a few weeks now which might be related to upgrading react native, but I am not sure how this should affect Fastlane.

Help would be appreciated.

```
+------------------------------------------------------------------------------+

| (0) deploy-to-itunesconnect-deliver@2                                        |
+------------------------------------------------------------------------------+
| id: deploy-to-itunesconnect-deliver                                          |
| version: 2.18.0                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-09-22T09:35:24Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[09:35:24]  * [OK] Step dependency (go) installed, available. 
Configs:
- IpaPath: /Users/vagrant/deploy/[REDACTED FOR GITHUB].ipa
- PkgPath: 
- ItunesconUser: [REDACTED]
- Password: *****
- AppPassword: *****
- AppID: [REDACTED FOR GITHUB]
- BundleID: 
- SubmitForReview: no
- SkipMetadata: yes
- SkipScreenshots: yes
- SkipAppVersionUpdate: no
- TeamID: [REDACTED FOR GITHUB]
- TeamName: 
- Platform: ios
- Options: 
- GemfilePath: ./Gemfile
- FastlaneVersion: latest-stable
- ITMSParameters: -t DAV
- VerboseLog: false
Connected Apple Developer Portal Account found, exposing FASTLANE_SESSION env var
Session exported
Setup
fastlane version defined: latest-stable, installing...
$ gem "install" "fastlane" "--no-document"
$ rbenv "rehash"
$ fastlane "-v"
fastlane installation at path:
/Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/bin/fastlane
-----------------------------
fastlane 2.152.0
#######################################################################
# fastlane 2.160.0 is available. You are on 2.152.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################
Setup took 220.850495 seconds to complete
Deploy
**Note:** if your password
contains special characters
and you experience problems, please
consider changing your password
to something with only
alphanumeric characters.
**Be advised**
that this step uses a well maintained, open source tool which
uses *undocumented and unsupported APIs* (because the current
iTunes Connect platform does not have a documented and supported API)
to perform the deployment.
This means that when the API changes
**this step might fail until the tool is updated**.
$ fastlane "deliver" "--username" "[REDACTED]" "--app" "[REDACTED FOR GITHUB]" "--team_id" "[REDACTED FOR GITHUB]" "--ipa" "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/ipaOrPkg923320700/tmp.ipa" "--skip_screenshots" "--skip_metadata" "--force" "--platform" "ios"
[09:39:19]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:39:23]: Sending anonymous analytics information
[09:39:23]: Learn more at https://docs.fastlane.tools/#metrics
[09:39:23]: No personal or sensitive data is sent.
[09:39:23]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[09:39:23]: Login to App Store Connect ([REDACTED])
[09:39:26]: Login successful
+--------------------------------------+----------------------------------------------------------------------------+
|                                              deliver 2.152.0 Summary                                              |
+--------------------------------------+----------------------------------------------------------------------------+
| username                             | [REDACTED]                                                  |
| team_id                              | [REDACTED FOR GITHUB]                                                                    |
| ipa                                  | /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/ipaOrPkg923320700/tmp.ipa |
| skip_screenshots                     | true                                                                       |
| skip_metadata                        | true                                                                       |
| force                                | true                                                                       |
| platform                             | ios                                                                        |
| app_identifier                       | [REDACTED FOR GITHUB]                                                      |
| screenshots_path                     | ./screenshots                                                              |
| metadata_path                        | ./metadata                                                                 |
| app_version                          | 1.3.1                                                                      |
| edit_live                            | false                                                                      |
| use_live_version                     | false                                                                      |
| skip_binary_upload                   | false                                                                      |
| skip_app_version_update              | false                                                                      |
| overwrite_screenshots                | false                                                                      |
| submit_for_review                    | false                                                                      |
| reject_if_possible                   | false                                                                      |
| automatic_release                    | false                                                                      |
| phased_release                       | false                                                                      |
| reset_ratings                        | false                                                                      |
| run_precheck_before_submit           | true                                                                       |
| precheck_default_rule_level          | warn                                                                       |
| ignore_language_directory_validation | false                                                                      |
| precheck_include_in_app_purchases    | true                                                                       |
+--------------------------------------+----------------------------------------------------------------------------+
[09:39:26]: Making sure the latest version on App Store Connect matches '1.3.1'...
timeout after 5400 seconds```

**Comment by mjones-droid** [comment]
Hi @EyMaddis!

Would you mind sending me a build where this is happening? Also, please enable support access on your app so I can dig deeper. 

https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/

Matthew
Senior Customer Engineer

**Comment by EyMaddis** [comment]
Hi @mjones-droid 
Thanks for getting back. Here is a build:
https://app.bitrise.io/build/826b98d47e6d0373#?tab=log

**Comment by mjones-droid** [comment]
Just to rule it out... Under the debug section of the step try switching the Fastlane Version to "latest".

**Comment by EyMaddis** [comment]
No difference unfortunately...

**Comment by mjones-droid** [comment]
Looking at your account, it looks like this issue is with a specific branch. Specifically when you compile from:
_feature/UNI-487-android-tv-with-focus-handling_.

It looks like you've never had a green build from that branch. You have however had green builds when running _/live/homeofhorror_ through the same workflow. 

Can you think of any differences between the two branches that might be causing this? I'm guessing there's an oddity in your project or scheme configuration that's causing this.

**Comment by EyMaddis** [comment]
I upgraded react-native which touched project files, but I am unsure how to debug it. It is especially weird since the Xcode archive step works.

**Comment by mjones-droid** [comment]
So if I understand correctly the build that doesn't work with the workflow was upgraded to react-native 0.62, but the build that does work was not updated? 

Also... Are you sure the application specific password is correct? Right now you have it set to the same thing as your AppStore Connect password...

**Comment by mjones-droid** [comment]
Hmmmm... That's interesting. 

The Deploy to iTunes step uses Fastlane. Given that the only thing that's really changed is the version of React Native being used, I wonder if there's a compatibility issue with the version of Fastlane (2.152.0).

In the deploy to iTunes step, try changing the value in "fastlane version" from "latest-stable" to "latest". Let's see if that makes a difference.

**Comment by EyMaddis** [comment]
I did, unfortunately no change

**Comment by mjones-droid** [comment]
May I have your permission to create a debug workflow on your account? Also, I'd like to connect to your build via remote access. Be aware that this will give me access to your source code.

**Comment by EyMaddis** [comment]
@mjones-droid Yes, that is ok :)

**Comment by mjones-droid** [comment]
I was able to get past the error in this build:
https://app.bitrise.io/build/1961e49071477cb0#?tab=log

This occurred after  flipping "Skip App Version Update?" to yes. The actual upload still failed because the value in the info.plist file was not higher than the previously uploaded version. 

So we've confirmed for sure that the issue causing the freeze is related to the "App Version Update". Doing some research, I've found other users having a similar issue with Fastlane (which powers the step). 

https://github.com/fastlane/fastlane/issues/15511

Please take a peek at that thread and see if anything there looks relevant to your specific build.

**Comment by EyMaddis** [comment]
Thank you so much, Matthew.

So I am not 100% sure what caused it, but Skip App Version Update is actually fine for. I think I just need to compare the build number in Xcode with AppStore Connect. 

Thanks :) 

For me personally, the issue is resolved. 
I just wonder whether the build step can at least provide more info to users about what is happing. 

Maybe some more log entries or a timeout could help.
I would be fine with closing this ticket :)

**Comment by EyMaddis** [comment]
So the problem seems to be back. This time it happens randomly. I have to same codebase and bitrise.yml for 3 apps and in the last few days some of them fail. Skip App Version Update is set and the version numbers match. 

I actually think that Apple is taking so long... the mail from the app store came around 2h after the start of the build. 
My guess is: AppStoreConnect is taking too long and "Skip Version Update" does not actually work.
In the issue you mentioned, @mjones-droid, they say that providing a changelog might block this from working. Does this step use changelogs and is there a way around it?

**Comment by mjones-droid** [comment]
Hey @EyMaddis!

To my knowledge the step does not use change logs. If you send me a recent failing build and [enable support access](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) I'd be happy to take another look. 

Matthew
Senior Customer Engineer
